oceanbase/obkv-table-client-java

pom.xml

fix pom.xml license info

---

pom.xml

fix: update default java.version from 1.6 to 1.8

fix: update default java.version from 1.6 to 1.8

---

pom.xml

update mysql-connector-java version to 5.1.49 and fastjson version to 1.2.79

fix: update mysql-connector-java version to 5.1.49 and fastjson version to 1.2.79

---

src/main/java/com/alipay/oceanbase/rpc/ObClusterTableAsyncQuery.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/syncquery/ObQueryOperationType.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/syncquery/ObTableQueryAsyncRequest.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/syncquery/ObTableQueryAsyncResult.java
src/main/java/com/alipay/oceanbase/rpc/stream/async/ObTableClientQueryAsyncStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/stream/async/ObTableQueryAsyncStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryAsyncImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableQueryAsyncImpl.java

Modify new add cpp file Copyright description

fix: modify file description

---

pom.xml

update release version to 0.1.2

update version to 0.1.2

---

pom.xml

update table client version to 0.1.3

update version to 0.1.3

---

pom.xml
src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObTableConnection.java
src/main/java/com/alipay/oceanbase/rpc/property/Property.java
src/main/java/com/alipay/oceanbase/rpc/table/AbstractObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientBatchOpsImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryImpl.java
src/main/java/com/alipay/oceanbase/rpc/util/MonitorUtil.java
src/main/resources/oceanbase-table-client/log/logback/log-conf.xml
src/test/java/com/alipay/oceanbase/rpc/ObTableClientTest.java

- release [obkv-table-client-java](https://github.com/oceanbase/obkv-table-client-java) 1.0.3
- bug fixes, learn more from release notes
N.A.
No
Pass all tests in observer 3.x

Release obkv-table-client-java 1.0.3

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/aggregation/ObTableAggregation.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/ObTableQuery.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryImpl.java
src/test/java/ci.sql
src/test/java/com/alipay/oceanbase/rpc/ObTableClientTest.java

增加了对多分区聚集的防御措施
不允许多分区聚集，添加防御措施
N/A
N/A
N/A
- [ ☑️] I've run the tests to see all new and existing tests pass.
- [ ☑️] If this Pull Request resolves an issue, I linked to the issue in the text above.
- [ ☑️] I've informed the technical writer about the documentation change if necessary.

[Fix] add defend of muliple partition aggregation

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/aggregation/ObTableAggregation.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/aggregation/ObTableAggregationResult.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/aggregation/ObTableAggregationType.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/ObTableQuery.java
src/test/java/ci.sql
src/test/java/com/alipay/oceanbase/rpc/ObTableClientTest.java

revise aggregation impl
add some test cases and revise aggregation impl
N/A
N/A
N/A
N/A

[Fix] revise aggregation impl

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/aggregation/ObTableAggregationResult.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientTest.java

modify test cases for aggregate on empty table.
modify test cases for aggregate on empty table.
N/A
N/A
N/A

[Fix] modify test cases for aggregate on empty table.

---

src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObPacketFactory.java
src/main/java/com/alipay/oceanbase/rpc/property/AbstractPropertyAware.java
src/main/java/com/alipay/oceanbase/rpc/property/Property.java
src/main/java/com/alipay/oceanbase/rpc/protocol/packet/ObRpcPacketHeader.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTable.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientTest.java

- Implement re-routing flag in RPC header (for ODP)
- Implement re-routing flag in RPC header in packet factory.
- Implement re-routing properties.
All tests except tests could not pass in 3.x.
N.A.
N.A.
N.A.

[Feat] reRouting flag

---

src/main/java/com/alipay/oceanbase/rpc/util/ObHashUtils.java
src/test/java/ci.sql
src/test/java/com/alipay/oceanbase/rpc/ObTableClientPartitionKeyTest.java

Fix int / tinyint / smallint in key partition table.
Transform short and byte into long for hash.

[Fix] int in key partition

---

src/main/java/com/alipay/oceanbase/rpc/ObGlobal.java
src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObTableConnection.java
src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java
src/main/java/com/alipay/oceanbase/rpc/protocol/packet/ObRpcPacketHeader.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/AbstractPayload.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/ObPayload.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/ObUnisVersion.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableAbstractOperationRequest.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableBatchOperationRequest.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableOperationRequest.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/mutate/ObTableQueryAndMutateRequest.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/ObNewRange.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/ObTableQueryRequest.java
src/main/java/com/alipay/oceanbase/rpc/util/ObHashUtils.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientAutoIncTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientCheckAndInsertTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableSQLAuditTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableTTLTest.java
src/test/java/com/alipay/oceanbase/rpc/table/ObTableConnectionTest.java

Refactor the ObVersion. Now we could get the majorVersion / minorVersion / buildVersion / revisionVersion in OB_VERSION.
Also, Fix a autoInc bug in ODP mode and refactor ObUnisVersion.
- Refactor ObVersion
- Refactor ObUnisVersion
- Fix auto Increment bug in ODP mode
Pass tests in ODP mode and direct mode in 4.x and 3.x

[Refactor] ObVersion

---

src/main/java/com/alipay/oceanbase/rpc/ObGlobal.java
src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObTableConnection.java
src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java
src/main/java/com/alipay/oceanbase/rpc/protocol/packet/ObRpcPacketHeader.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableAbstractOperationRequest.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableBatchOperationRequest.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableOperationRequest.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/mutate/ObTableQueryAndMutateRequest.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/ObNewRange.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/ObTableQueryRequest.java
src/main/java/com/alipay/oceanbase/rpc/util/ObHashUtils.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientAutoIncTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientCheckAndInsertTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientPartitionKeyTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableSQLAuditTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableTTLTest.java
src/test/java/com/alipay/oceanbase/rpc/table/ObTableConnectionTest.java

- Fix testLargeQuery in 3.x
- Refactor OB_VERSION
- Fix testLargeQuery in 3.x
- Refactor OB_VERSION

[Fix] testLargeQuery and OB_VERSION

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/ObObjType.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientTest.java

- Fix date time
- Fix date time

[Fix] datetime

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/mutation/InsertOrUpdate.java
src/main/java/com/alipay/oceanbase/rpc/mutation/MutationFactory.java
src/main/java/com/alipay/oceanbase/rpc/mutation/Put.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableAbstractOperationRequest.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableBatchOperationRequest.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableOperationRequest.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableOptionFlag.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTable.java
src/main/java/com/alipay/oceanbase/rpc/table/api/Table.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientTest.java

- support put in insertOrUpdate
- add Put() interface

support put

---

src/main/java/com/alipay/oceanbase/rpc/ObGlobal.java
src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java
src/main/java/com/alipay/oceanbase/rpc/mutation/InsertOrUpdate.java
src/main/java/com/alipay/oceanbase/rpc/mutation/MutationFactory.java
src/main/java/com/alipay/oceanbase/rpc/mutation/Put.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/ObObjType.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableBatchOperationRequest.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableOperationRequest.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableOptionFlag.java
src/main/java/com/alipay/oceanbase/rpc/stream/ObTableClientQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTable.java
src/main/java/com/alipay/oceanbase/rpc/table/api/Table.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientPartitionKeyTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientTest.java

[Chore] format

---

src/test/java/com/alipay/oceanbase/rpc/ObTableTTLTest.java

Enable basic TTL test in 4.x
Enable basic TTL test in 4.x

[Test] enable basic TTL test in 4.x

---

pom.xml
src/main/java/com/alipay/oceanbase/rpc/table/ObTable.java

Update dependencies.
Update dependencies.

[Chore] update dependencies

---

src/test/java/com/alipay/oceanbase/rpc/ObTableClientTest.java

Fix ODP test cases
Fix ODP test cases

[Fix] ODP test case

---

src/test/java/com/alipay/oceanbase/rpc/ObTableClientAutoIncTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientCheckAndInsertTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableConnectionTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableSQLAuditTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableTTLTest.java
src/test/java/com/alipay/oceanbase/rpc/ObWeakReadConsistencyTest.java
src/test/java/com/alipay/oceanbase/rpc/table/ObTableConnectionTest.java
src/test/java/com/alipay/oceanbase/rpc/util/ObTableClientTestUtil.java

[Fix] test cases

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/ObAddr.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/direct_load/ObTableDirectLoadRequest.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableDirectLoad.java

* [Fix] table direct load rpc timeout

[Fix] table direct load rpc timeout

---

src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientAutoIncTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableConnectionTest.java
src/test/java/com/alipay/oceanbase/rpc/util/ObTableClientTestUtil.java

- Test in ODP mode
- Fix login in CE with ODP
- Test in ODP mode
- Fix login in CE with ODP

[Fix] CE login with ODP

---

src/test/java/com/alipay/oceanbase/rpc/ObTableClientTest.java

Add batch with same rowkey test
Add batch with same rowkey test

[Test] add batch test

---

README.md
src/test/java/com/alipay/oceanbase/rpc/ObTableClientTest.java

- Add append/increment test in batch operation
- Add append/increment test in batch operation

[Test] apd/inc in batch op

---

src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObTableRemoting.java
src/test/java/ci.sql

- check credential before encode

check credential before encode

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java
src/main/java/com/alipay/oceanbase/rpc/util/MonitorUtil.java
src/test/java/ci.sql
src/test/java/com/alipay/oceanbase/rpc/ObTableClientTest.java

obkv connection bugfix
obkv connection bugfix
obkv connection bugfix

obkv connection bugfix

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java

delete row element precheck
delete row element precheck
delete row element precheck

delete row element precheck

---

src/main/java/com/alipay/oceanbase/rpc/table/api/TableQuery.java

incorrect comment
incorrect comment
incorrect comment

incorrect comment

---

src/test/java/com/alipay/oceanbase/rpc/ObTableCheckAndInsUpTest.java

add a cross-partition test for checkAndInsUp batch operation

[Test] add cross-partition test for checkAndInsUp

---

src/test/java/com/alipay/oceanbase/rpc/ObTableCheckAndInsUpTest.java

Add a test for checkAndInsUp using non-partitioned table.

[Test] add checkAndInsUp test for non-partitioned table

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/location/model/TableEntry.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/AbstractQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableParam.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientPartitionKeyTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientPartitionRangeTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientTest.java
src/test/java/com/alipay/oceanbase/rpc/util/ObTableClientTestUtil.java
src/test/resources/ci.sql

- Fix subpartition in query
- Fix subpartition in query

[Fix] sub partition in query

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableBatchOperation.java
src/test/java/com/alipay/oceanbase/rpc/ObAtomicBatchOperationTest.java

增加same_property_names判断

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/ObObjType.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientTest.java
src/test/resources/ci.sql

- Fix time scale
- Now we support timestamp(6) / timestamp(3) / timestamp / datetime(6) / datetime(3) / datetime
- Fix time scale

[Fix] time scale

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/location/model/partition/ObHashPartDesc.java
src/main/java/com/alipay/oceanbase/rpc/location/model/partition/ObKeyPartDesc.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientPartitionKeyTest.java
src/test/java/com/alipay/oceanbase/rpc/location/model/partition/ObKeyPartDescTest.java
src/test/resources/ci.sql

- Fix query in sub-partition
- Fix key partition 
- Fix query in sub-partition
- Fix key partition

[Fix] sub part query & key part

---

src/main/java/com/alipay/oceanbase/rpc/mutation/BatchOperation.java
src/main/java/com/alipay/oceanbase/rpc/mutation/result/MutationResult.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/ObRowKey.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableBatchOperationResult.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableLSOpRequest.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableLSOpResult.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableLSOperation.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableOperationResult.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableOperationType.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOp.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOpEntity.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOpFlag.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOpQuery.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOpResult.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableTabletOp.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableTabletOpFlag.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableTabletOpResult.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java
src/test/resources/ci.sql

- Support dict column name
- Support dict column name, use bitmap instead of string in LS operation

[Feat] dict column name

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/property/Property.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableLSOperation.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableTabletOp.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTable.java
src/test/java/com/alipay/oceanbase/rpc/ObTableCheckAndInsUpTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientTest.java
src/test/resources/ci.sql

- Fix property in ObTableClient
- Fix order of the column name in LSOp
- Fix property in ObTableClient
- Fix order of the column name in LSOp

[Fix] property & hashset in LSOp

---

src/main/java/com/alipay/oceanbase/rpc/location/model/partition/ObRangePartDesc.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientPartitionRangeTest.java
src/test/resources/ci.sql

- The client will throw an exception when data is not in any partition in the range part
- The client will throw an exception when data is not in any partition in the range part.

[Fix] upperBound in range part

---

src/test/java/com/alipay/oceanbase/rpc/ObTableTTLTest.java
src/test/resources/ci.sql

- Add test case for limit and offset in scan
- Add test case for limit and offset in scan

[Test] test case for limit & offset

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableOperationType.java
src/test/java/com/alipay/oceanbase/rpc/ObTablePutTest.java
src/test/resources/ci.sql

add tests for put impl

---

src/main/java/com/alipay/oceanbase/rpc/mutation/BatchOperation.java

support batch put

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java
src/main/java/com/alipay/oceanbase/rpc/stream/ObTableClientQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryImpl.java
src/test/java/com/alipay/oceanbase/rpc/hbase/ObHTableOperationRequest.java
src/test/java/com/alipay/oceanbase/rpc/hbase/ObHTableTest.java

table group route in hbase
table group route in hbase
table group route in hbase

ohbase table group route

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java
src/test/java/com/alipay/oceanbase/rpc/hbase/ObHTableTest.java

- Fix null pointer exception (authored by @foronedream)
- Fix null pointer exception

[Fix] null pointer exception in TableGroup

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableLSOpFlag.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java
src/main/java/com/alipay/oceanbase/rpc/util/Serialization.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientTest.java

- Reduce memory used by calculating the payload size of the String
- Reduce memory used by calculating the payload size of the String

[Refactor] payloadSize of String

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/AbstractQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/stream/ObTableClientQueryAsyncStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/stream/ObTableClientQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTable.java
src/test/java/com/alipay/oceanbase/rpc/ObTableTTLTest.java

- Fix async query in ODP mode
- Fix async query in ODP mode

[Fix] ODP async query

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/AbstractQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/syncquery/ObQueryOperationType.java
src/main/java/com/alipay/oceanbase/rpc/stream/ObTableClientQueryAsyncStreamResult.java
src/test/java/com/alipay/oceanbase/rpc/bolt/ObTableClientTestBase.java

- Add close() in async query
- Add close() in async query

[Fix] async query close

---

src/test/java/com/alipay/oceanbase/rpc/ObTableClientTest.java
src/test/java/com/alipay/oceanbase/rpc/hbase/ObHTableOperationRequest.java
src/test/java/com/alipay/oceanbase/rpc/hbase/ObHTableTest.java

- Fix test case
- Fix test case

[Chore] test case

---

README.md
example/simple-kv-demo/pom.xml
example/simple-mutation/pom.xml
example/simple-table-demo/pom.xml

- update README.md
- update README.md

[Chore] update README.md

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/mutation/BatchOperation.java
src/main/java/com/alipay/oceanbase/rpc/mutation/Increment.java
src/main/java/com/alipay/oceanbase/rpc/mutation/Insert.java
src/main/java/com/alipay/oceanbase/rpc/mutation/InsertOrUpdate.java
src/main/java/com/alipay/oceanbase/rpc/mutation/Mutation.java
src/main/java/com/alipay/oceanbase/rpc/mutation/Put.java
src/main/java/com/alipay/oceanbase/rpc/mutation/Replace.java
src/main/java/com/alipay/oceanbase/rpc/mutation/Update.java
src/main/java/com/alipay/oceanbase/rpc/mutation/result/BatchOperationResult.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableOperation.java

- Adapt hbase put
- Adapt hbase put

adapt Hbase put ls op (#117)

---

src/main/java/com/alipay/oceanbase/rpc/ObGlobal.java
src/main/java/com/alipay/oceanbase/rpc/mutation/BatchOperation.java

- Update the supported version of lsop
- Update the supported version of lsop

[Chore] update supported version of lsop

---

src/test/java/com/alipay/oceanbase/rpc/ObTableAuditTest.java
src/test/java/com/alipay/oceanbase/rpc/util/ObTableClientTestUtil.java
src/test/resources/ci.sql

add sql audit tests

---

src/test/java/com/alipay/oceanbase/rpc/ObTableClientAutoIncTest.java

Fix the ObTableClientAutoIncTest.testAutoIncrementNotRowkey testcase 
some assertion in the test case are wrong

[Fix] the ObTableClientAutoIncTest.testAutoIncrementNotRowkey testcase

---

src/main/java/com/alipay/oceanbase/rpc/mutation/BatchOperation.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableAbstractOperationRequest.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableLSOpRequest.java
src/main/java/com/alipay/oceanbase/rpc/table/AbstractTableBatchOps.java
src/main/java/com/alipay/oceanbase/rpc/table/AbstractTableQuery.java
src/test/java/com/alipay/oceanbase/rpc/ObTableModeTest.java

- adapt ob_kv_mode and add tests
- TabeAPI use KV entity type

adapt ob_kv_mode

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObTableConnection.java
src/main/java/com/alipay/oceanbase/rpc/property/Property.java
src/main/java/com/alipay/oceanbase/rpc/table/AbstractObTable.java
src/main/java/com/alipay/oceanbase/rpc/table/AbstractObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTable.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientInfoTest.java
src/test/java/com/alipay/oceanbase/rpc/util/ObTableClientTestUtil.java

client adapt for system view kv_client_info

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObTableRemoting.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientBatchOpsImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java
src/test/java/com/alipay/oceanbase/rpc/bolt/ObTableTest.java
src/test/java/com/alipay/oceanbase/rpc/hbase/ObHTableTest.java
src/test/java/com/alipay/oceanbase/rpc/table/ObTableConnectionTest.java

1. In addition to rerouting on wrong errors, determine if upper-level route refresh retry is needed based on error codes.  
2. Migrated the retry logic implemented in batch operations to single operations.

Refactor Retry Strategy: Adapt Retry Logic for Single Operations

---

src/main/java/com/alipay/oceanbase/rpc/property/Property.java

modify default value of MAX_CONN_EXPIRED_TIME

---

pom.xml
src/main/java/com/alipay/oceanbase/rpc/ObClusterTableQuery.java
src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/bolt/protocol/ObTablePacketCode.java
src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObTableRemoting.java
src/main/java/com/alipay/oceanbase/rpc/location/model/ObReplicaType.java
src/main/java/com/alipay/oceanbase/rpc/location/model/RouteTableRefresher.java
src/main/java/com/alipay/oceanbase/rpc/property/AbstractPropertyAware.java
src/main/java/com/alipay/oceanbase/rpc/property/Property.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObAddr.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObAddrVersion.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableApiMove.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableMoveReplicaInfo.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/AbstractQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTable.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientBatchOpsImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java
src/main/java/com/alipay/oceanbase/rpc/util/MonitorUtil.java
src/test/java/com/alipay/oceanbase/rpc/location/reroute/RerouteTest.java
src/test/java/com/alipay/oceanbase/rpc/location/reroute/util/Partition.java
src/test/java/com/alipay/oceanbase/rpc/location/reroute/util/Replica.java
src/test/java/com/alipay/oceanbase/rpc/location/reroute/util/ReplicaOperation.java

reroute_job_test

---

src/test/java/com/alipay/oceanbase/rpc/ObTableClientAutoIncTest.java
src/test/resources/ci.sql

add test case for has auto-increment column in batch operation

---

src/test/java/com/alipay/oceanbase/rpc/ObTableGroupCommitTest.java

add test case for group commit sys view

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java

Fixed the issue where the ObTable component configuration was not properly rebuilt on route refresh

resolve issue with ObTable configuration being empty on route refresh

---

src/main/java/com/alipay/oceanbase/rpc/ObGlobal.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java

TableGroup Routing Support: 
+ The LSOP now supports the passing of tablegroup for calculating routes, improving the routing logic and allowing for more flexible configurations.
Version Update for LSOP Support: 
+ The LSOP has been updated to support the 4.3.4 version specifications, ensuring compatibility with recent changes and improvements

lsop support tablegroup

---

src/main/java/com/alipay/oceanbase/rpc/ObGlobal.java

update lsOp and returnOneResult support version

update lsOp and returnOneResult support version

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java

fix null pointer exeception when client close

fix null pointer exeception when client close

---

src/main/java/com/alipay/oceanbase/rpc/table/ObTable.java

fix issue #195

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java

setRpcExecuteTimeout access null ptr
Check if empty before access.

[fix] setRpcExecuteTimeout access null ptr

---

src/test/java/com/alipay/oceanbase/rpc/ObTableGlobalIndexTest.java

add test case for global index and auto split

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java

fix 3.x incompatible
Distinguish sql parameter between version 3.x and 4.x

[fix] 3.x compatible

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/AbstractQueryStreamResult.java

fix global index route refresh wrong when route need refresh

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryImpl.java

hbase tablename bug fix

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryImpl.java

hbase empty family scan error

---

src/main/java/com/alipay/oceanbase/rpc/table/ObHBaseParams.java

[fix] add hbase version param

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/AbstractQueryStreamResult.java

fix global index route wrong when need partial route refresh

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/AbstractQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/syncquery/ObQueryOperationType.java
src/main/java/com/alipay/oceanbase/rpc/stream/ObTableClientQueryAsyncStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryImpl.java

support hbase version 2.x for obkv-hbase-client
1. support hbase scan renewLease 
2. other bugfix

feature: hbase compatible 2.x

---

src/main/java/com/alipay/oceanbase/rpc/table/ObTable.java

fix: error OB_TENANT_NOT_IN_SERVER and try to refresh route after relogin

---

src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObTableConnection.java

throw exception when failed to get server version from login result

---

src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObConnectionFactory.java

remove references to BoltLoggerFactory

---

pom.xml

Obkv table client 1.3.0.1 shaded

---

pom.xml

Obkv table client 1.3.0 shaded

---

src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java

fix lsop nullPoint bug

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/get/Get.java
src/main/java/com/alipay/oceanbase/rpc/get/result/GetResult.java
src/main/java/com/alipay/oceanbase/rpc/mutation/BatchOperation.java
src/main/java/com/alipay/oceanbase/rpc/mutation/result/BatchOperationResult.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java
src/test/java/com/alipay/oceanbase/rpc/ObTableGetTest.java
src/test/resources/ci.sql

add get interface

---

src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java

After DDL (Data Definition Language) operations, the first request may encounter a routing error, causing the table to retry the erroneous operation (op). During this process, when reorganizing the failed op, the original op ID is not recorded. Instead, the position of ops is reset and starts from 0 again. This can lead to duplicate reception of results for certain positions while other positions never receive results, ultimately causing a null pointer exception when processing the results.

Lsop index bugfix

---

src/main/java/com/alipay/oceanbase/rpc/mutation/BatchOperation.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java

- resolve some bugs caused by mismatched operation types

resolve some bugs caused by mismatched operation types

---

src/main/java/com/alipay/oceanbase/rpc/util/MonitorUtil.java

fix monitor log print too much

---

src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObTableConnection.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTable.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientBatchOpsImpl.java

fix and opt for some exceptions process

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java

opt for print refresh table entry log

---

src/main/java/com/alipay/oceanbase/rpc/checkandmutate/CheckAndInsUp.java

- fix null pointer in CheckAndInsUp

fix null pointer in CheckAndInsUp

---

src/main/java/com/alipay/oceanbase/rpc/property/Property.java

- change some default value of parameter

change some default value of parameter

---

src/main/java/com/alipay/oceanbase/rpc/ObGlobal.java
src/main/java/com/alipay/oceanbase/rpc/direct_load/protocol/v0/ObDirectLoadProtocolV0.java
src/main/java/com/alipay/oceanbase/rpc/mutation/BatchOperation.java
src/main/java/com/alipay/oceanbase/rpc/mutation/result/MutationResult.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableLSOpRequest.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableOperationType.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOp.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOpEntity.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOpQuery.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableTabletOp.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/ObTableQuery.java
src/main/java/com/alipay/oceanbase/rpc/table/ObHBaseParams.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryImpl.java

This client has supported OBKV HBase Get feature in LSOp.
Adjust ObTableSingelOp, ObTableSingelOpQuery and ObTableClientLSBatchOpsImpl to OBKV HBase Get. ObTableSingelOpQuery will carry elements required by OBKV HBase Get and ObTableClientLSBatchOpsImpl will send them to server.

Hbase Batch Get Support

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/AbstractQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientBatchOpsImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java

improve batch performance by removing unnecessary sleep after parameter adjustment

Fix batch wait

---

src/main/java/com/alipay/oceanbase/rpc/property/Property.java

revert rpc.execute.timeout

---

src/main/java/com/alipay/oceanbase/rpc/ObGlobal.java

`isHBaseBatchGetSupport` Add version 4351

enable batch get on 4351

---

src/main/java/com/alipay/oceanbase/rpc/ObClusterTableQuery.java
src/main/java/com/alipay/oceanbase/rpc/ObGlobal.java
src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/ObTableObjType.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObIndexType.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/ObTableQuery.java
src/main/java/com/alipay/oceanbase/rpc/stream/ObTableClientQueryAsyncStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/table/AbstractTableQueryImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObFTSParams.java
src/main/java/com/alipay/oceanbase/rpc/table/ObKVParams.java
src/main/java/com/alipay/oceanbase/rpc/table/ObKVParamsBase.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/api/TableQuery.java
src/test/java/com/alipay/oceanbase/rpc/ObTableFullTextIndexTest.java
src/test/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/ObTableQueryPayloadTest.java

[feat] obkv support full text search

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/ObObjType.java
src/test/java/com/alipay/oceanbase/rpc/ObTableDatetimeTest.java
src/test/resources/ci.sql

support mysql date/datetime

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableQueryAndMutateFlag.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOpFlag.java

support user_specific_T flag for ObTableQueryAndMutate and ObTableSingleOp

feat: support user_specific_T flag for ObTableQueryAndMutate and ObTableSingleOp

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/parser/ObGeneratedColumnExpressParser.java

fix sub expr bug

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java

Resolved an issue where the route refresh did not catch the ObTableServerCacheExpiredException, leading to persistent errors in subsequent operations. Added proper exception handling to ensure stability.

fix: handle ObTableServerCacheExpiredException on route refresh to prevent continuous errors  

---

src/test/java/com/alipay/oceanbase/rpc/ObTableFullTextIndexTest.java

add fts case

---

src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java

- Leverage JVM classloading guarantees for one-time initialization
- Simplify implementation using static initialization block

Move JDBC driver loading to static initializer

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/parser/ObGeneratedColumnExpressParser.java

fix some bugs

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java
src/main/java/com/alipay/oceanbase/rpc/stream/ObTableClientQueryAsyncStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/stream/ObTableClientQueryStreamResult.java

fix query get addr expired or scale down refresh failed

Capture exceptions in the refreshIndexInfo and do syncRefreshMetadata

---

src/main/java/com/alipay/oceanbase/rpc/ObGlobal.java
src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObConnectionFactory.java
src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObTableConnection.java
src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObTableRemoting.java
src/main/java/com/alipay/oceanbase/rpc/checkandmutate/CheckAndInsUp.java
src/main/java/com/alipay/oceanbase/rpc/direct_load/ObDirectLoadConnection.java
src/main/java/com/alipay/oceanbase/rpc/get/Get.java
src/main/java/com/alipay/oceanbase/rpc/get/result/GetResult.java
src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java
src/main/java/com/alipay/oceanbase/rpc/location/model/partition/ObPartitionLocationInfo.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/column/ObGeneratedColumnNegateFunc.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableQueryAndMutateFlag.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOpFlag.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/AbstractQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/stream/ObTableClientQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/table/ObFTSParams.java
src/main/java/com/alipay/oceanbase/rpc/table/ObKVParamsBase.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTable.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientBatchOpsImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientType.java
src/main/java/com/alipay/oceanbase/rpc/table/api/Table.java
src/test/java/com/alipay/oceanbase/rpc/ODPGetPartitionMetaTest.java
src/test/java/com/alipay/oceanbase/rpc/ObGetPartitionTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableFullTextIndexTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableGetTest.java
src/test/java/com/alipay/oceanbase/rpc/bolt/ObTableTest.java
src/test/java/com/alipay/oceanbase/rpc/protocol/payload/impl/column/ObGeneratedColumnNegateFuncTest.java

- add client type & remove some ObTableServerCapacity

add client type & remove some ObTableServerCapacity

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/mutation/BatchOperation.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOp.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/mutate/ObTableQueryAndMutate.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java

mutation,query_and_mutate set a isUserSpecifiedT based on T

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java

- set partition id invalid when isDistributedExecuteSupported

set partition id invalid when isDistributedExecuteSupported

---

src/main/java/com/alipay/oceanbase/rpc/mutation/BatchOperation.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableOperationType.java
src/main/java/com/alipay/oceanbase/rpc/queryandmutate/QueryAndMutate.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java

add query_and_mutate check_and_mutate

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/column/ObGeneratedColumnAbsFunc.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/parser/ObGeneratedColumnExpressParser.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/parser/ObGeneratedColumnFuncName.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/parser/ObGeneratedColumnSimpleToken.java

support abs func

---

src/test/java/com/alipay/oceanbase/rpc/ObKVFeatureModeTest.java

add config item test for secondary part

---

README.md
pom.xml
src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/exception/ObTableEntryRefreshException.java
src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/ObObjType.java
src/main/java/com/alipay/oceanbase/rpc/stream/ObTableClientQueryAsyncStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/stream/ObTableClientQueryStreamResult.java
src/test/java/com/alipay/oceanbase/rpc/ObTableDatetimeTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableFullTextIndexTest.java
src/test/java/com/alipay/oceanbase/rpc/bolt/ObTableClientTestBase.java
src/test/java/com/alipay/oceanbase/rpc/util/ObTableHotkeyThrottleUtil.java
src/test/resources/ci.sql

Secondary part rebase master

---

src/main/java/com/alipay/oceanbase/rpc/ObGlobal.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableServerCapacity.java

add version check for distributed execute

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/AbstractQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientBatchOpsImpl.java

remove retry in odp mode when meet exception

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java

fix ClientType Incompatible

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/syncquery/ObTableQueryAsyncRequest.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryImpl.java

fix allowDistributeScan default value

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java

fix client type odp mode

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java

During the initialization phase, perform two login operations: the first login retrieves the version; if it’s an HBase model and supports secondary partitioning, perform another login to obtain the server-side capability configuration.

Fix compatibility issues with legacy ODP versions

---

src/main/java/com/alipay/oceanbase/rpc/direct_load/ObDirectLoadStatement.java
src/main/java/com/alipay/oceanbase/rpc/direct_load/execution/ObDirectLoadStatementDetachTask.java
src/main/java/com/alipay/oceanbase/rpc/direct_load/execution/ObDirectLoadStatementExecutor.java
src/main/java/com/alipay/oceanbase/rpc/direct_load/protocol/ObDirectLoadProtocol.java
src/main/java/com/alipay/oceanbase/rpc/direct_load/protocol/payload/ObDirectLoadDetachRpc.java
src/main/java/com/alipay/oceanbase/rpc/direct_load/protocol/v0/ObDirectLoadProtocolV0.java
src/main/java/com/alipay/oceanbase/rpc/direct_load/protocol/v0/payload/ObDirectLoadDetachRpcV0.java
src/main/java/com/alipay/oceanbase/rpc/direct_load/protocol/v0/payload/impl/ObTableDirectLoadDetachArg.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/direct_load/ObTableDirectLoadOperationType.java

direct load support detach task

[feat] direct load support detach task

---

src/main/java/com/alipay/oceanbase/rpc/direct_load/protocol/v0/ObDirectLoadProtocolV0.java

fix direct load detach version control
4.2.5.4 -> 4.2.5.3

fix direct load detach version control

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/AbstractPayload.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/ObObjType.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/ObTableObjType.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/ObTableSerialUtil.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableLSOpRequest.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableLSOperation.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOp.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOpEntity.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOpQuery.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableTabletOp.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/ObHTableFilter.java
src/main/java/com/alipay/oceanbase/rpc/table/ObFTSParams.java
src/main/java/com/alipay/oceanbase/rpc/table/ObHBaseParams.java
src/main/java/com/alipay/oceanbase/rpc/table/ObKVParams.java
src/main/java/com/alipay/oceanbase/rpc/table/ObKVParamsBase.java
src/main/java/com/alipay/oceanbase/rpc/util/Serialization.java
src/test/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableLsOperationRequestTest.java

lsop encode opt

---

src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObTableRemoting.java

fix print log wrong

---

src/main/java/com/alipay/oceanbase/rpc/location/model/OcpResponseData.java
src/main/java/com/alipay/oceanbase/rpc/location/model/OcpResponseDataIDC.java

Jackson needs to set annotation for JSON members, add annotation for IDC.

add json annotation for IDC

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java

Retry queryAndMutate in odp mode when meeting some exceptions like OB_TRY_LOCK_ROW_CONFLICT, OB_TRANSACTION_SET_VIOLATION etc.

Retry queryAndMutate operation in odp mode

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOpEntity.java

Fix Get gets empty result and throw out-of-bound exception when getResult.

Fix empty propertiesValue out of bound

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/bolt/protocol/ObTablePacketCode.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/Pcodes.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObHbaseQTV.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObHbaseRequest.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObHbaseResult.java

hbase new protocal

---

src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryImpl.java

Fix HBase getscanners in odp mode.

Fix hbase getscanners in hbase mode

---

pom.xml
src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObTableConnection.java
src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java
src/main/java/com/alipay/oceanbase/rpc/location/model/OcpResponse.java
src/main/java/com/alipay/oceanbase/rpc/location/model/OcpResponseData.java
src/main/java/com/alipay/oceanbase/rpc/location/model/OcpResponseDataIDC.java
src/main/java/com/alipay/oceanbase/rpc/location/model/OcpResponseDataRs.java
src/main/java/com/alipay/oceanbase/rpc/util/MonitorUtil.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientInfoTest.java

Replace Fastjson with Jackson.

Replace Fastjson with Jackson

---

src/main/java/com/alipay/oceanbase/rpc/location/model/RouteTableRefresher.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTable.java

Server must be added into suspect list and checked alive if it is set as dirty, otherwise the server may maintain dirty status forever.

Set dirty and add ip to suspect list, set valid when remove from suspect list

---

src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObTableConnection.java

modify log level when do reconnect

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/AbstractPayload.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableLSOpRequest.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableLSOperation.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOp.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOpEntity.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOpQuery.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableTabletOp.java

fix lsop encode error

---

src/main/java/com/alipay/oceanbase/rpc/ObGlobal.java

4355 does not support hbase put performance improvement and other features in 441, add version control for 4355.

Set version control for 4355 
