oceanbase/obkv-table-client-java

src/main/java/com/alipay/oceanbase/rpc/stream/ObTableClientQueryStreamResult.java

Fixed: class java.lang.IllegalArgumentException cannot be cast to class com.alipay.oceanbase.rpc.exception.ObTableException 
Get the class of the exception then use different methods to print the log.

[Fix] unrecognized exception in ODP query

---

README.md
src/main/java/com/alipay/oceanbase/rpc/table/ObTable.java

Add init check for obtable.
Add init check for obtable.

[Fix] obtable init check

---

src/test/java/com/alipay/oceanbase/rpc/ObTableClientAutoIncTest.java
src/test/java/com/alipay/oceanbase/rpc/bolt/ObTableClientTestBase.java

Fix test cases.
Fix test cases.

[Fix] test case

---

src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableOperation.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/api/TableQuery.java
src/main/java/com/alipay/oceanbase/rpc/util/MonitorUtil.java
src/test/java/com/alipay/oceanbase/rpc/ObTableAggregationTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientAutoIncTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientTest.java

obkv-client:check tenant name after connect && insert null into auto-increment key column
obkv-client:check tenant name after connect && insert null into auto-increment key column
obkv-client:check tenant name after connect && insert null into auto-increment key column
obkv-client:check tenant name after connect && insert null into auto-increment key column

obkv-client:check tenant name after connect && insert null into auto-increment key column

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java

bug:
when do query with primary index and specify the indexName with `primary`，the client will regard it is a secondary index and to judge if it is a global index.
when indexName is NULL or is equal to 'primary' (ignore case), skip to judge if it is a global index

fix: query with primary index fail when indexname specify to 'primary'

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/bolt/protocol/ObTablePacketCode.java
src/main/java/com/alipay/oceanbase/rpc/checkandmutate/CheckAndInsUp.java
src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java
src/main/java/com/alipay/oceanbase/rpc/location/model/ObIndexInfo.java
src/main/java/com/alipay/oceanbase/rpc/mutation/BatchOperation.java
src/main/java/com/alipay/oceanbase/rpc/mutation/Mutation.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/AbstractPayload.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/Pcodes.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObIndexType.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableAbstractOperationRequest.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableLSOpFlag.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableLSOpRequest.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableLSOpResult.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableLSOperation.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableQueryAndMutateFlag.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOp.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOpType.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableTabletOp.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableTabletOpFlag.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableTabletOpResult.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/mutate/ObTableQueryAndMutate.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTable.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryAsyncImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/api/Table.java
src/main/java/com/alipay/oceanbase/rpc/util/MonitorUtil.java
src/test/java/com/alipay/oceanbase/rpc/ObTableCheckAndInsUpTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableGlobalIndexTest.java

In this pull request, We implemented a new interface checkAndInsUp, which means that insert up operations are performed only if the check is successful, and this interface is useful in some cases, such as asynchronous log synchronization in different clusters, need to check the timestamp of the data, and only allow newer operations to be performed.
We added some flags in obTableQueryAndMutate and reused this rpc message to pass the check and execute semantics, and the obkv server will perform this rpc call and return a response to the client. In addition, in order to support batch checking and modification and improve throughput, we implement a new batch rpc message format ObTableLSOpRequest.

[Feat] support checkAndInsUp

---

src/test/java/com/alipay/oceanbase/rpc/ObTableClientTest.java

refresh Java test case error code
observer will return `OB_NOT_SUPPORTED` when do increment or append op with  no-specified column type

fix test case error code not match

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/location/model/TableEntry.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableLSOperation.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientBatchOpsImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableParam.java
src/test/java/com/alipay/oceanbase/rpc/ObTableAggregationTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableCheckAndInsUpTest.java

- Fix refresh table entry when the table has been truncated
- Fix refresh table entry when the table has been truncated

[Fix] refresh when truncate table

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableLSOpRequest.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableLSOperation.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableOperationType.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOp.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOpEntity.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOpFlag.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOpQuery.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableTabletOp.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java

adjust the message format of ObLSOp for better performance

[Chore] Adjust ObLSOp Format

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/ObObj.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/ObTableObjType.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/ObTableSerialUtil.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOpEntity.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOpQuery.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableTabletOpResult.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/ObNewRange.java
src/test/java/com/alipay/oceanbase/rpc/ObTableCheckAndInsUpTest.java
src/test/resources/ci.sql

[Feat] support obkv object format

---

src/main/java/com/alipay/oceanbase/rpc/mutation/BatchOperation.java

Fix the exception message when execute LS batch is inaccurate

[Fix] the exception message when execute LS batch is inaccurate

---

src/main/java/com/alipay/oceanbase/rpc/location/model/partition/ObRangePartDesc.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableOperationType.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOp.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientPartitionRangeTest.java

- Fix query encoding in singleOperation
- Fix query encoding in singleOperation

[Fix] query in singleOperation

---

src/main/java/com/alipay/oceanbase/rpc/ObClusterTableBatchOps.java
src/main/java/com/alipay/oceanbase/rpc/mutation/BatchOperation.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableBatchOperation.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableBatchOperationRequest.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableOptionFlag.java
src/main/java/com/alipay/oceanbase/rpc/table/AbstractTableBatchOps.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableBatchOpsImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientBatchOpsImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/api/TableBatchOps.java
src/test/java/com/alipay/oceanbase/rpc/ObAtomicBatchOperationTest.java

batch operation add option flag to return one result, reduce the size of rpc package
1. add RETURN_ONE_RES in ObTableOptionFlag

add option flag, batch operations can return one res

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/checkandmutate/CheckAndInsUp.java
src/main/java/com/alipay/oceanbase/rpc/mutation/Append.java
src/main/java/com/alipay/oceanbase/rpc/mutation/BatchOperation.java
src/main/java/com/alipay/oceanbase/rpc/mutation/Delete.java
src/main/java/com/alipay/oceanbase/rpc/mutation/Increment.java
src/main/java/com/alipay/oceanbase/rpc/mutation/Insert.java
src/main/java/com/alipay/oceanbase/rpc/mutation/InsertOrUpdate.java
src/main/java/com/alipay/oceanbase/rpc/mutation/Replace.java
src/main/java/com/alipay/oceanbase/rpc/mutation/Update.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientBatchOpsImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryImpl.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientTest.java

check empty table name
check empty table name
check empty table name in client

check empty table name in client

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/bolt/protocol/ObTablePacketCode.java
src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObTableRemoting.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/Pcodes.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/AbstractQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/stream/ObTableClientQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/stream/async/ObTableClientQueryAsyncStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/table/AbstractTableQueryImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryAsyncImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryImpl.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableGlobalIndexTest.java

bugfixs:
1. client return "Unknown Rpc command code value ,4388" when observer and client enable rerouting
2. java client  cannot support rpc result compressed
3. global index route refresh wrong when need to retry refresh table entry

bugfixs: compress && rerouting not supported And global index route refresh wrong when retry

---

src/main/java/com/alipay/oceanbase/rpc/mutation/BatchOperation.java

fix batch put use correct api

---

src/main/java/com/alipay/oceanbase/rpc/ObClusterTableBatchOps.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientBatchOpsImpl.java
src/test/java/com/alipay/oceanbase/rpc/ObAtomicBatchOperationTest.java

fix return_one_result flag not return one result
When returning the package, merge the results of each partition.

fix return_one_result flag not return one result

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/ObTableObjType.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableLSOperation.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java
src/test/java/com/alipay/oceanbase/rpc/ObTableLsBatchTest.java
src/test/resources/ci.sql

adapt to lob-related table object type and add related testcases

[Fix] adapt to lob-related table object type

---

src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObPacketFactory.java
src/test/java/com/alipay/oceanbase/rpc/ObAtomicBatchOperationTest.java

After the tenant migration, the odp mode has been reported as access wrong tenant not supported, and a large number of 4007
1. Fix rpcHeaderPacket prv_tenantid = TenantId
2. add batch get test case

Fix prv tenantid always 1

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableTabletOp.java

Fix isSamePropertiesNames flag in ObTableTabletOp is wrong

Fix isSamePropertiesNames flag in ObTableTabletOp is wrong

---

src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryImpl.java

- Fix partitionObTables in ODP client
- Fix partitionObTables in ODP client

[Fix] partitionObTables in ODP client

---

src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java

fix: get table entry location from remote may be timeout when the partition nums too large

fix get location from remote timeout

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableLSOpFlag.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableLSOperation.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientTest.java
src/test/resources/ci.sql

when use get operation with empty select columns in batch, it will return indexOutRange exception caused by the name bitmap is not correct.

[Bugfix] batch get select empty return error

---

src/test/java/com/alipay/oceanbase/rpc/ObTableErrMsgTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableIndexWithCalcColumn.java
src/test/resources/ci.sql

add test cases for 4377 errors:
- local index with virtual generated columns
- global index with virual generated columns
- rowkey with autoincrment column is not filled when do delete or update

add test cases for 4377 error

---

src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java

In ODP mode, if a cross-partition request fails partially, the obproxy will return the first error code. The client will catch the exception and retry, causing the original successful requests to be executed repeatedly, thus executing repeatedly.

fix: execute result duplicated when do ls batch in odp mode

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/location/model/partition/ObHashPartDesc.java
src/main/java/com/alipay/oceanbase/rpc/location/model/partition/ObKeyPartDesc.java
src/main/java/com/alipay/oceanbase/rpc/location/model/partition/ObPartDesc.java
src/main/java/com/alipay/oceanbase/rpc/location/model/partition/ObRangePartDesc.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryImpl.java
src/test/java/com/alipay/oceanbase/rpc/ObTableAggregationTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableClientPartitionKeyTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableIndexWithCalcColumn.java

- Fix min/max in partition table
- Fix min/max in partition table

[Fix] extendType/min/max in scan

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/ResultCodes.java

change error code OB_KV_HBASE_CONVERT_INT_ERROR to OB_KV_HBASE_INCR_FIELD_IS_NOT_LONG accord to observer
change error code OB_KV_HBASE_CONVERT_INT_ERROR to OB_KV_HBASE_INCR_FIELD_IS_NOT_LONG accord to observer

[Chore] change error code OB_KV_HBASE_CONVERT_INT_ERROR to OB_KV_HBASE_INCR_FIELD_IS_NOT_LONG accord to observer

---

src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryImpl.java

support reverse scan global order when more partitions
Send requests by partition in reverse order

support reverse scan global order

---

src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObTableConnection.java

fix: relogin invalid when MAX_CONN_EXPIRED_TIME > 2

fix: relogin invalid when MAX_CONN_EXPIRED_TIME > 2

---

src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObTableRemoting.java

When a tenant does not exist, directly capturing the error code and retrying will never succeed due to the use of the old tenant ID. In this case, the client needs to re-login for authentication. 
We should no longer retry this error code and instead return it directly to the client.

remove unneeded retry codes

---

src/main/java/com/alipay/oceanbase/rpc/ObClusterTableBatchOps.java
src/main/java/com/alipay/oceanbase/rpc/ObGlobal.java
src/main/java/com/alipay/oceanbase/rpc/mutation/BatchOperation.java
src/test/java/com/alipay/oceanbase/rpc/ObAtomicBatchOperationTest.java
src/test/java/com/alipay/oceanbase/rpc/ObTableLsBatchTest.java

Add check when setReturnOneResult is true but observer is nor supported and it will throw Exception

fix returnOneResult is not support in ob 421

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java

Restored the `getOrRefreshTableEntry` interface to support external usage requirements. This change effectively disables the `fetchAll` parameter in the overloaded method, ensuring backward compatibility and proper operation for external dependencies.

Restore getOrRefreshTableEntry interface

---

src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObTableConnection.java

- Added logic to check if configsMap is empty when no parameters are provided by the caller.  
- Prevent JSON generation to avoid creating an empty object.  
- Updated comments to clarify the behavior when parameters are missing.

fix: Avoid JSON generation when configsMap is empty  

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/ObHTableFilter.java
src/test/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/ObTableQueryPayloadTest.java

Fix bytes in htable filter string changed after convert byte[] to String
use byte[] instead of String to store filter String to ensure the byte is the same as user-passed

[Fix] bytes in htable filter string changed after convert byte[] to String

---

src/main/java/com/alipay/oceanbase/rpc/ObClusterTableQuery.java
src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/bolt/protocol/ObTablePacketCode.java
src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObTableRemoting.java
src/main/java/com/alipay/oceanbase/rpc/location/model/ObReplicaType.java
src/main/java/com/alipay/oceanbase/rpc/location/model/RouteTableRefresher.java
src/main/java/com/alipay/oceanbase/rpc/property/AbstractPropertyAware.java
src/main/java/com/alipay/oceanbase/rpc/property/Property.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObAddr.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObAddrVersion.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableApiMove.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableMoveReplicaInfo.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/AbstractQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTable.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientBatchOpsImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java
src/main/java/com/alipay/oceanbase/rpc/util/MonitorUtil.java
src/test/java/com/alipay/oceanbase/rpc/location/reroute/RerouteTest.java
src/test/java/com/alipay/oceanbase/rpc/location/reroute/util/Partition.java
src/test/java/com/alipay/oceanbase/rpc/location/reroute/util/Replica.java
src/test/java/com/alipay/oceanbase/rpc/location/reroute/util/ReplicaOperation.java

OBKV JAVA secondary routing design, Scan request timeout parameter addition, and slow query log not enabled by default

Log performance optimization, scan timeout, and secondary routing

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/AbstractQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryImpl.java

Fix the issue of reverse scan result errors caused by unordered partition inserts due to HashMap, the solution is to replace HashMap with LinkedHashMap.

fix: correct reverse-scan results affected by retry logic

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java
src/main/java/com/alipay/oceanbase/rpc/location/model/partition/ObPartitionLocationInfo.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/AbstractQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/stream/ObTableClientQueryAsyncStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/stream/ObTableClientQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java

This bugfix introduces a retry mechanism to handle routing errors in executeMutation, SyncQuery, and QueryAndMutate operations.
Optimizes the logic for partial refresh, reducing the degree of thread blocking during startup. As a result, the original performance levels are restored.
By capturing specific error codes, determine when to refresh routing information and update tablet location.
This enhancement ensures that operations can recover from scenarios involving truncation, splitting, and disaster recovery, thereby improving system robustness and reliability.

feature: Optimize partial refresh and add retry for executeMutation/query

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/AbstractQueryStreamResult.java

fix test case throw null exception
1. partition id in 3.x and 4.x should be dealt in different way
2. fix some other problem

fix 3.x null exception

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/AbstractQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/syncquery/ObQueryOperationType.java
src/main/java/com/alipay/oceanbase/rpc/stream/ObTableClientQueryAsyncStreamResult.java

support hbase scan renewLease
add a new interface for hbase

support hbase scan renewLease

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java
src/main/java/com/alipay/oceanbase/rpc/location/model/TableEntry.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/AbstractQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/syncquery/ObQueryOperationType.java
src/main/java/com/alipay/oceanbase/rpc/stream/ObTableClientQueryAsyncStreamResult.java

Fix the issue where the tablet_id is incorrect when the partition table has a single partition.
Each time when fetching the tableEntry, retrieve the partition information once. When distinguishing partitioned tables, you can do so based on the number of partitions or the partition information

Fix the issue where the tablet_id is incorrect when the partition table has a single partition

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java
src/main/java/com/alipay/oceanbase/rpc/location/model/TableEntry.java

Fix the issue where the tablet_id is incorrect when the partition table num is 1

Partition error

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientBatchOpsImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java

distinguish observer version when calling getOrRefreshPartitionInfo

[fix] test case stuck in await

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/AbstractQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/stream/ObTableClientQueryAsyncStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryImpl.java

Fix global route refresh wrong

---

src/main/java/com/alipay/oceanbase/rpc/direct_load/protocol/v0/ObDirectLoadProtocolV0.java

Direct-load already supports specified partition level load, but the obkv client has not yet released the check for specified partitions. This PR mainly modified the version check information related to the specified partition
modify version control for direct-load partition

modify version control for direct-load partition

---

src/main/java/com/alipay/oceanbase/rpc/table/ObHBaseParams.java

[fix] add hbase version param

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/ObTableSingleOpEntity.java

properties value could be in wrong order after prepare for multiple times.
map properties name to value.

[fix] properties value in wrong order

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/AbstractQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryImpl.java

The indexName in quey process is the real tableName. Need to set the indexName and get tableEntry.

fix error hbase table name because of the lack of indexTableName

---

src/main/java/com/alipay/oceanbase/rpc/property/Property.java

- change RPC_OPERATION_TIMEOUT default value from 10 seconds to 2 second

change RPC_OPERATION_TIMEOUT default value from 10 seconds to 2 second

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObTableRemoting.java
src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java
src/main/java/com/alipay/oceanbase/rpc/location/model/TableEntry.java
src/main/java/com/alipay/oceanbase/rpc/location/model/partition/ObPartitionEntry.java
src/main/java/com/alipay/oceanbase/rpc/location/model/partition/ObPartitionLocationInfo.java
src/main/java/com/alipay/oceanbase/rpc/property/Property.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/ObObjType.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/AbstractQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/stream/ObTableClientQueryAsyncStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/stream/ObTableClientQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientBatchOpsImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryImpl.java

This feature primarily implements a single-tablet refresh mechanism for table location and adds some retry mechanisms to support the auto-splitting feature.
- The table location management in 4.x is separated and managed independently using ObPartitionLocationInfo, with index management based on tablet IDs in ObPartitionEntry.
- The refresh of metadata and the refresh of location are decoupled into **two phases**. When a routing change is encountered, the location information is refreshed at a single-tablet granularity.
- A retry mechanism has been added to refresh the entire table entry for certain error codes and appropriately handle requests that require retries (e.g., splitting and recombining batches) to ensure the reliability and correctness of the retries.

route single partition refresh

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/AbstractQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientBatchOpsImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryImpl.java
src/test/java/com/alipay/oceanbase/rpc/ObGetPartitionTest.java

This merge fixes compatibility problem caused by getPartition in ODP mode. The ODP versions before 4.3.2 does not support getPartition function and query with part_id. The ODP versions before 4.3.2 will return OB_NOT_SUPPORT if using these two functions. Other functions are not impacted.

Fix compatibility problem caused by getPartition in ODP mode

---

src/main/java/com/alipay/oceanbase/rpc/property/Property.java

- Revert the default connection pool size to 1, cause performance rollback

Revert the default connection pool size to 1

---

src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObTableRemoting.java

- refresh route table when server return OB_GTS_NOT_READY, same with go client

refresh route table when server return OB_GTS_NOT_READY

---

src/main/java/com/alipay/oceanbase/rpc/direct_load/ObDirectLoadStatement.java

modify direct-load MAX_QUERY_TIMEOUT to Integer.MAX_VALUE
modify direct-load MAX_QUERY_TIMEOUT to INT_MAX, to avoid issues with incorrect parameter settings due to the MAX_QUERY_TIMEOUT being set beyond the integer limit.

modify direct-load MAX_QUERY_TIMEOUT to Integer.MAX_VALUE

---

src/main/java/com/alipay/oceanbase/rpc/direct_load/ObDirectLoadConnection.java

In a poor network environment, the connection time exceeds the default connection timeout (1s).
add set connect timeout interface on ObDirectLoadConnect

direct load set connect timeout

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObTableConnection.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/column/ObGeneratedColumnNegateFunc.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/parser/ObGeneratedColumnExpressParser.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTable.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableServerCapacity.java
src/test/java/com/alipay/oceanbase/rpc/protocol/payload/impl/column/ObGeneratedColumnNegateFuncTest.java

support sync server capacity and negate expr
Added support for parsing negation expressions, and enhanced the server-side capabilities in the `obTable`. Each time the server capability is evaluated, the `serverCapacity` is retrieved from the `obTable` for assessment.

support sync server capacity and negate expr

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/exception/ObTableEntryRefreshException.java
src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java

Add an inactive state to RefreshException, set it only when JDBC connection fails.

Fix issue where low traffic prevents timely detection and refresh of RS when the peer goes offline

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java
src/test/java/com/alipay/oceanbase/rpc/bolt/ObTableClientTestBase.java
src/test/java/com/alipay/oceanbase/rpc/util/ObTableHotkeyThrottleUtil.java

Fix long-time down after kill the leader observer, instantly refresh address roster and location to ensure the stability.

Fix ob down ls timeout

---

src/main/java/com/alipay/oceanbase/rpc/table/ObHBaseParams.java

change obhbaseParams defualt param
change allowPartialResults to false defualt

change obhbaseParams defualt param

---

src/main/java/com/alipay/oceanbase/rpc/ObClusterTableQuery.java
src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/syncquery/ObTableQueryAsyncRequest.java
src/main/java/com/alipay/oceanbase/rpc/stream/ObTableClientQueryAsyncStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryImpl.java
src/test/java/com/alipay/oceanbase/rpc/ObTableDatetimeTest.java

fix hbase multi partition scan return repetitive data

[Fix] hbase multi partition scan return repetitive data

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/AbstractQueryStreamResult.java

fix scan 4007 erase table group cache nullptr

fix erase table group get nullptr

---

src/main/java/com/alipay/oceanbase/rpc/direct_load/ObDirectLoadConnection.java

It is not safe to access ObGlobal.OB_VERSION when creating ObDirectLoadConnection in parallel.
issue: https://github.com/oceanbase/obkv-table-client-java/issues/230
access ObGlobal.OB_VERSION in synchronized

fix obVersion in direct load

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObTableConnection.java
src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java
src/main/java/com/alipay/oceanbase/rpc/location/model/RouteTableRefresher.java
src/main/java/com/alipay/oceanbase/rpc/location/model/TableLocations.java
src/main/java/com/alipay/oceanbase/rpc/location/model/TableRoute.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/AbstractQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTable.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientBatchOpsImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java

This merge is to remove all the debug log from refactor_table_routing branch.
Remove all redundant logs.

Remove redundant debug log

---

src/main/java/com/alipay/oceanbase/rpc/exception/ObTableException.java
src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java

OB_TRANS_TIMEOUT need to retry by client when executing until the server is ready. SQL exception from getting tenant id or ob version should refresh observer lists.

Retry ob trans timeout and SQL exception

---

example/simple-table-demo/src/main/java/com/oceanbase/example/ObDirectLoadDemo.java
src/main/java/com/alipay/oceanbase/rpc/direct_load/ObDirectLoadConnection.java
src/main/java/com/alipay/oceanbase/rpc/direct_load/ObDirectLoadStatement.java
src/main/java/com/alipay/oceanbase/rpc/direct_load/ObDirectLoadTraceId.java
src/main/java/com/alipay/oceanbase/rpc/direct_load/execution/ObDirectLoadStatementExecutionId.java
src/main/java/com/alipay/oceanbase/rpc/direct_load/execution/ObDirectLoadStatementExecutor.java
src/main/java/com/alipay/oceanbase/rpc/direct_load/execution/ObDirectLoadStatementWriteTask.java

Fix the following issues:
* In multi node write mode, the write node cannot exit when the direct load task fails. [2024101100104675941]
* In multi node write mode, the trace id of the write node is inconsistent with that of the master node. [2025041100108177768]
* Statement close before the write operation is completed, resulting in a null pointer exception.

fix direct load multi node write

---

src/main/java/com/alipay/oceanbase/rpc/location/model/TableLocations.java

The new table client use runtimeMaxWait to control the retry process, not tryTimes. In odp mode, it does not break out the retry loop after fetching the table entry, which causes timeout.
Return the table entry after refreshing in odp mode.

Fix odp mode fail to force refresh partition meta

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/AbstractQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientBatchOpsImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java

In odp mode, table not exist error should be directly thrown and do not retry.
Do not use retry-type exception to retry table not exist error in odp mode.

Fix table not exist retry too long in odp mode

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/AbstractQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/stream/ObTableClientQueryAsyncStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientBatchOpsImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java

Use different exception to avoid retry is not a good idea, because maybe the specific exception is depended outside.
In odp mode, it will not retry in the table client judged by the mode inside.

Fix odp mode use different exception to avoid retry

---

src/main/java/com/alipay/oceanbase/rpc/location/model/OdpInfo.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTable.java

In disaster recovery situation, if one of the servers gets unavailable for service, the new client will set the server as dirty and avoid to access to it again until it becomes available. But in odp mode, the client should not to set proxy's address as dirty, otherwise the proxy will never recover to valid.
In odp mode, do not set dirty to proxy's address. Disaster recovery policy should be implemented by the odp side.

Fix odp set dirty

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/location/model/TableLocations.java
src/main/java/com/alipay/oceanbase/rpc/location/model/TableRoute.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientQueryImpl.java

In new table client, the routing interfaces have been unified to the same for the ODP mode or OCP mode, but sometimes old versions of ODP cannot support new protocol of the routing process and there is no way to obtain the version of ODP in advance. So the routing interfaces have been separated, and the ODP routing interfaces are only used by getPartition relative methods.

Fix 431 version of ODP use normal get and throw error NOT_SUPPORT

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/bolt/protocol/ObTablePacketCode.java
src/main/java/com/alipay/oceanbase/rpc/meta/ObTableMetaRequest.java
src/main/java/com/alipay/oceanbase/rpc/meta/ObTableMetaResponse.java
src/main/java/com/alipay/oceanbase/rpc/meta/ObTableRpcMetaType.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/Pcodes.java

MetaExecutor interface definition and demo

---

src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/ObTableQuery.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/ObTableQueryFlag.java

support hot only scan
support hot only scan, the original pr is https://github.com/oceanbase/obkv-table-client-java/pull/328

[Feat] support hot only scan

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/location/model/TableRoute.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java

Fix TableQuery cannot refresh tablet location when location changed.

Fix TableQuery cannot refresh tablet location

---

src/main/java/com/alipay/oceanbase/rpc/location/model/TableRoute.java

Throw the original exception when initRoster failed and the cause is the same. The error code will be carried by the exception.

throw the same type original Exception when login

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/bolt/transport/ObTableConnection.java
src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java
src/main/java/com/alipay/oceanbase/rpc/location/model/RouteTableRefresher.java
src/main/java/com/alipay/oceanbase/rpc/location/model/TableRoster.java
src/main/java/com/alipay/oceanbase/rpc/location/model/TableRoute.java
src/main/java/com/alipay/oceanbase/rpc/protocol/payload/impl/execute/query/AbstractQueryStreamResult.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTable.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientBatchOpsImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java

In low ops disaster recovery situation, table client need to remove the old observer connection in time. Otherwise when the observer recovers, netty connection may not identify the validity of the tcp connection and keep reporting error. Keep-alive mechanic guarantees to remove the old cache in time.

Background keep-alive mechannic

---

src/main/java/com/alipay/oceanbase/rpc/location/model/TableLocations.java

Jackson cannot serialize ObPartitionKey in bounds of range part, need to disable FAIL_ON_EMPTY_BEANS.

Fix debug log jackson range part error

---

src/main/java/com/alipay/oceanbase/rpc/mutation/Mutation.java
src/test/java/com/alipay/oceanbase/rpc/ObHeapTableModel1Test.java
src/test/java/com/alipay/oceanbase/rpc/ObHeapTableModel2Test.java
src/test/java/com/alipay/oceanbase/rpc/ObHeapTableModel3Test.java
src/test/java/com/alipay/oceanbase/rpc/ObHeapTableModel4Test.java
src/test/java/com/alipay/oceanbase/rpc/ObHeapTableModel5Test.java
src/test/java/com/alipay/oceanbase/rpc/ObHeapTableModel6Test.java
src/test/java/com/alipay/oceanbase/rpc/ObHeapTableModel7Test.java
src/test/java/com/alipay/oceanbase/rpc/ObHeapTableModel8Test.java

- support heap table & add tests

heap table tests

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientBatchOpsImpl.java
src/main/java/com/alipay/oceanbase/rpc/table/ObTableClientLSBatchOpsImpl.java

Should not refresh tableEntry if require_rerouting is true in odp mode

Fix refresh tableEntry if require_rerouting is true in odp mode

---

example/simple-table-demo/src/main/java/com/oceanbase/example/ObDirectLoadDemo.java
src/main/java/com/alipay/oceanbase/rpc/direct_load/ObDirectLoadStatement.java
src/main/java/com/alipay/oceanbase/rpc/direct_load/execution/ObDirectLoadStatementExecutor.java

add new interfaces to support peer node and abort

add new interfaces to P2P Mode

---

src/main/java/com/alipay/oceanbase/rpc/location/LocationUtil.java

Socket timeout error caused by HTTP GET ConfigServer content  is logged as an inappropriate level and may cause WARNING in production environment. Need to lower the log level of this situation because it's not that severe.

Lower configServer error log level when throw out SocketTimeoutException

---

src/main/java/com/alipay/oceanbase/rpc/ObTableClient.java

New put execution is not added into retry processor before, need to add new put execution into it.

Add new put into retry structure
